### Login and get token
# @name auth
POST {{base_url}}:7001/api/auth/login
Content-Type: application/json

{
  "email":"a@b.com",
  "password":"Aa.1234"
}

### Get all products
GET {{base_url}}:7002/api/products
Authorization: Bearer {{auth.response.body.$.token.token}}