### Login and get token
# @name auth
POST https://localhost:7001/api/auth/login
Content-Type: application/json

{
  "email":"a@b.com",
  "password":"Aa.1234"
}

### Get all products
GET https://localhost:7002/api/products
Authorization: Bearer {{auth.response.body.$.token.token}}