### Login and get token
# @name auth
POST {{base_url}}:7001/api/auth/login
Content-Type: application/json

{
  "email":"a@b.com",
  "password":"Aa.1234"
}

### save_token
@response = JSON.parse(responseBody).token.token;
client.global.set("TOKEN", response.token.token);
