### register
POST {{base_url}}:7001/api/auth/register
Content-Type: application/json

{
  "email": "aa@b.com",
  "password": "Aa.1234",
  "confirmPassword": "Aa.1234",
  "firstName": "Test One",
  "lastName": "User"
}