### sign in
POST http://localhost:7001/api/auth/register
Content-Type: application/json

{
  "email": "a@b.com",
  "password": "A.1234",
  "confirmPassword": "A.1234",
  "firstName": "Test One",
  "lastName": "User"
}